# Site settings
title: Kadirhan Ucar
description: "kadirhan@ucar:~#"
baseurl: "/" # for test: remove string '/space-jekyll-template' to ''
url: "kdrhnucr.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: Kadirhan Ucar
user_title: Kadirhan Ucar
email: kadirhanucars@gmail.com
twitter_username: UcarKadirhan
github_username:  kdrhnucr
discord_invite: fp6YDqqyVz # Example: Discord server invite gg extension like in 'https://discord.gg/cj5rg'
linkedin_public_url: kadirhan-ucar # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
profile_picture: https://avatars.githubusercontent.com/u/79535417?s=400&u=cce24eca65b94184aa833b00777966a0b6afd46a&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    - title: series
      url: /series
      key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 4
    - title: about me
      url: /about
      key_trigger: 5

# projects in header index
projects:
  - name: Python3 Port Scanner
    url: https://github.com/kdrhnucr/python3-port-scanner
  - name: Python3 Strong Password Generator
    url: https://github.com/kdrhnucr/python3-strong-password-generator
    
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
